export const strings = Object.freeze({
  appName: 'QR Recast',
  privacyNote: 'Your photos and QR contents never leave your device.',
  camera: {
    viewfinderLabel: 'QR camera scanner',
    idleTitle: 'Ready to scan',
    idleBody: 'Start the camera or upload an image from this device.',
    pendingTitle: 'Opening camera',
    pendingBody: 'Waiting for camera access.',
    deniedTitle: 'Camera blocked',
    deniedBody: 'Allow camera access in browser settings, or upload an image instead.',
    unsupportedTitle: 'Camera unavailable',
    unsupportedBody: 'Upload an image from this device instead.',
    errorTitle: 'Camera paused',
    errorBody: 'Try again or upload an image from this device.',
    start: 'Start camera',
    upload: 'Upload image',
    hint: 'Point at a QR code',
    torchOn: 'Turn torch on',
    torchOff: 'Turn torch off',
    torchError: 'Torch is not available for this camera.',
    flip: 'Flip camera',
    noCode: 'No QR code was found in that image.',
    uploadError: 'The image could not be read.',
  },
  result: {
    loading: 'Preparing result',
    title: 'Recast QR',
    supporting: 'Export a clean copy of the code you scanned.',
    qrAlt: 'Recast QR code',
    generating: 'Generating QR code',
    svg: 'SVG',
    png: 'PNG',
    pdf: 'PDF',
    docx: 'DOCX',
    shareUrl: 'Share URL',
    showText: 'Show text',
    scanAgain: 'Scan again',
    decodedText: 'Decoded text',
    closeText: 'Close decoded text',
    emptyPayload: 'Empty payload',
    saved: 'Saved',
    shared: 'Shared',
    copied: 'Copied',
    cancelled: 'Cancelled',
    qrError: 'The QR code could not be generated.',
    exportError: 'That export could not be created.',
    urlTooLarge: 'This payload is too large to share as a URL.',
  },
  theme: {
    menuLabel: 'Choose colour scheme',
    system: 'System',
    light: 'Light',
    dark: 'Dark',
  },
});
