export const strings = Object.freeze({
  appName: 'QR Recast',
  privacyNote: 'Your photos and QR contents never leave your device.',
  ads: {
    label: 'Advertisement slot',
    placeholder: 'Advertisement',
  },
  about: {
    label: 'About QR Recast',
    title: 'About QR Recast',
    close: 'Close about',
    versionLabel: 'Version',
    privacyBody:
      'Photos, decoded QR text, generated URLs, filenames, hashes, image data, and exported files stay out of analytics.',
    analyticsTitle: 'Analytics',
    analyticsToggle: 'Share anonymised usage events',
    analyticsEnabled:
      'Analytics is on. Events use fixed metadata only, such as payload kind and export format.',
    analyticsOptedOut: 'Analytics is off on this device.',
    analyticsDoNotTrack: 'Your browser Do Not Track preference is on, so analytics stays off.',
    analyticsNotConfigured:
      'Analytics is not configured for this build, and this preference will still be remembered.',
    licence: 'MIT licence',
  },
  camera: {
    viewfinderLabel: 'QR camera scanner',
    idleTitle: 'Ready to scan',
    idleBody: 'Start the camera or upload an image from this device.',
    pendingTitle: 'Opening camera',
    pendingBody: 'Waiting for camera access.',
    deniedTitle: 'Camera blocked',
    deniedBody: 'Allow camera access in browser settings, or upload an image instead.',
    unsupportedTitle: 'Camera unavailable',
    unsupportedBody: 'Upload an image from this device instead.',
    errorTitle: 'Camera paused',
    errorBody: 'Try again or upload an image from this device.',
    start: 'Start camera',
    upload: 'Upload image',
    hint: 'Point at a QR code',
    torchOn: 'Turn torch on',
    torchOff: 'Turn torch off',
    torchError: 'Torch is not available for this camera.',
    flip: 'Flip camera',
    noCode: 'No QR code was found in that image.',
    uploadError: 'The image could not be read.',
  },
  result: {
    loading: 'Preparing result',
    title: 'Recast QR',
    supporting: 'Export a clean copy of the code you scanned.',
    qrAlt: 'Recast QR code',
    generating: 'Generating QR code',
    svg: 'SVG',
    png: 'PNG',
    pdf: 'PDF',
    docx: 'DOCX',
    shareUrl: 'Share URL',
    copyUrl: 'Copy URL',
    copiedUrl: 'Copied URL',
    copiedUrlPreview: 'Copied URL preview',
    shareUrlQrAlt: 'Share URL QR code',
    generatingShareUrlQr: 'Generating share URL QR code',
    payloadKinds: {
      text: 'Plain text',
      url: 'URL',
      wifi: 'Wi-Fi',
      vcard: 'vCard',
      calendar: 'Calendar event',
      email: 'Email',
      phone: 'Phone',
      sms: 'SMS',
      geo: 'Location',
    },
    openLink: 'Open link',
    copyText: 'Copy text',
    showText: 'Show text',
    scanAgain: 'Scan again',
    decodedText: 'Decoded text',
    closeText: 'Close decoded text',
    emptyPayload: 'Empty payload',
    saved: 'Saved',
    shared: 'Shared',
    copied: 'Copied',
    cancelled: 'Cancelled',
    qrError: 'The QR code could not be generated.',
    exportError: 'That export could not be created.',
    copyError: 'The text could not be copied.',
    shareUrlError: 'The share URL could not be prepared.',
    urlTooLarge: 'This payload is too large to share as a URL.',
    urlTooLargeGuidance:
      'URL sharing is disabled because this payload creates a link over 2000 characters. Export the QR or show the decoded text instead.',
  },
  theme: {
    menuLabel: 'Choose colour scheme',
    system: 'System',
    light: 'Light',
    dark: 'Dark',
  },
});
