export const strings = Object.freeze({
  appName: 'QR Recast',
  privacyNote: 'Your photos and QR contents never leave your device.',
  ads: {
    label: 'Advertisement slot',
    placeholder: 'Advertisement',
  },
  common: {
    no: 'No',
    yes: 'Yes',
  },
  about: {
    label: 'Settings',
    title: 'Settings',
    close: 'Close settings',
    versionLabel: 'Version',
    buildLabel: 'Build',
    privacyBody:
      'Photos, decoded QR text, generated URLs, filenames, hashes, image data, exported files, and Batch Recast storage stay on this device and out of analytics.',
    brandingTitle: 'Branding',
    brandingToggle: 'Brand QR exports',
    brandingStatus:
      'Branding is on by default and stays on this device; each Result can still override it.',
    batchTitle: 'Batch Recast',
    batchEmpty: 'No batch codes are saved on this device.',
    batchOne: '{count} batch code is saved on this device.',
    batchMany: '{count} batch codes are saved on this device.',
    batchStorage: 'Batch names, order, and payload metadata stay in this browser localStorage.',
    startBatch: 'Start batch',
    resumeBatch: 'Resume batch',
    clearBatch: 'Clear batch',
    analyticsTitle: 'Analytics',
    analyticsToggle: 'Share anonymised usage events',
    analyticsEnabled:
      'Analytics is on. Events use fixed metadata only, such as payload kind and export format.',
    analyticsOptedOut: 'Analytics is off on this device.',
    analyticsDoNotTrack: 'Your browser Do Not Track preference is on, so analytics stays off.',
    analyticsNotConfigured:
      'Analytics is not configured for this build, and this preference will still be remembered.',
    licence: 'MIT licence',
  },
  camera: {
    viewfinderLabel: 'QR camera scanner',
    idleTitle: 'Point at a QR code',
    idleBody: 'Start the camera, then line up a QR code in the frame.',
    pendingTitle: 'Opening camera',
    pendingBody: 'Waiting for camera access.',
    deniedTitle: 'Camera blocked',
    deniedBody: 'Allow camera access in browser settings, or upload an image instead.',
    unsupportedTitle: 'Camera unavailable',
    unsupportedBody: 'Upload an image from this device instead.',
    errorTitle: 'Camera paused',
    errorBody: 'Try again or upload an image from this device.',
    start: 'Start camera',
    upload: 'Upload image',
    hint: 'Point at a QR code',
    torchOn: 'Turn torch on',
    torchOff: 'Turn torch off',
    torchError: 'Torch is not available for this camera.',
    flip: 'Flip camera',
    noCode: 'No QR code was found in that image.',
    uploadError: 'The image could not be read.',
  },
  batch: {
    addError: 'That code could not be added.',
    addCode: 'Add code',
    added: 'Added to batch',
    batch: 'Batch',
    clear: 'Clear',
    clearBody: 'Remove every saved batch code from this device.',
    clearTitle: 'Clear batch?',
    closeName: 'Close name dialog',
    countShort: '{count} saved',
    delete: 'Delete',
    deleted: 'Code removed',
    drag: 'Drag to reorder',
    duplicate: 'That code is already in this batch.',
    emptyBody: 'Start scanning or upload an image to add the first code.',
    emptyTitle: 'No batch codes yet',
    export: 'Export batch',
    exportError: 'The batch export could not be created.',
    keepScanning: 'Keep scanning',
    manyCodes: '{count} codes saved',
    modeLabel: 'Capture mode',
    moveDown: 'Move down',
    moveUp: 'Move up',
    nameLabel: 'Name',
    nameTitle: 'Name this code',
    oneCode: '{count} code saved',
    persistenceError: 'This batch could not be saved on this device.',
    restored: 'Code restored',
    saveName: 'Save name',
    scanning: 'Scanning now',
    single: 'Single',
    startScanning: 'Start scanning',
    thumbnail: 'Batch QR thumbnail',
    title: 'Batch Recast',
    undo: 'Undo',
  },
  result: {
    loading: 'Preparing result',
    title: 'Your recast QR',
    supporting: 'Clean, private, and ready to share or save.',
    qrAlt: 'Recast QR code',
    generating: 'Generating QR code',
    copyQrAction: 'Copy QR image as PNG',
    copyQrTooltip: 'Hold QR to copy PNG',
    svg: 'SVG',
    png: 'PNG',
    pdf: 'PDF',
    docx: 'DOCX',
    download: 'Download',
    shareUrl: 'Share URL',
    copyUrl: 'Copy URL',
    copiedUrl: 'Copied URL',
    copiedUrlPreview: 'Copied URL preview',
    shareUrlQrAlt: 'Share URL QR code',
    generatingShareUrlQr: 'Generating share URL QR code',
    payloadKinds: {
      text: 'Plain text',
      url: 'Web address',
      wifi: 'Wi-Fi',
      vcard: 'vCard',
      calendar: 'Calendar event',
      email: 'Email',
      phone: 'Phone',
      sms: 'SMS',
      geo: 'Location',
      matter: 'Matter device',
      homekit: 'Apple Home accessory',
      crypto: 'Crypto payment',
      app: 'App link',
    },
    openLink: 'Open link',
    copyText: 'Copy text',
    copyValue: 'Copy value',
    showText: 'Show text',
    scanAgain: 'Scan again',
    brandingToggle: 'Brand this QR',
    detailsTitle: 'Detected details',
    decodedText: 'Decoded text',
    rawPayload: 'Raw payload',
    closeText: 'Close decoded text',
    emptyPayload: 'Empty payload',
    hiddenValue: 'Hidden',
    hideValue: 'Hide value',
    revealValue: 'Reveal value',
    valueCopied: 'Value copied',
    saved: 'Saved',
    shared: 'Shared',
    copied: 'Copied',
    qrCopied: 'QR image copied',
    cancelled: 'Cancelled',
    qrError: 'The QR code could not be generated.',
    exportError: 'That export could not be created.',
    copyError: 'The text could not be copied.',
    qrCopyError: 'The QR image could not be copied.',
    shareUrlError: 'The share URL could not be prepared.',
    urlTooLarge: 'This payload is too large to share as a URL.',
    urlTooLargeGuidance:
      'URL sharing is disabled because this payload creates a link over 2000 characters. Export the QR or show the decoded text instead.',
  },
  theme: {
    menuLabel: 'Toggle colour scheme',
    title: 'Colour scheme',
    light: 'Light',
    dark: 'Dark',
    toggleLabel: 'Toggle between light and dark',
  },
  qrTypes: {
    types: {
      appLink: 'App link',
      calendar: 'Calendar event',
      contact: 'Contact card',
      crypto: 'Crypto payment',
      email: 'Email',
      geo: 'Location',
      homekit: 'Apple Home accessory',
      matter: 'Matter device',
      plainText: 'Plain text',
      sms: 'SMS or MMS',
      telephone: 'Telephone number',
      url: 'Web address',
      wifi: 'Wi-Fi network',
    },
    fields: {
      address: 'Address',
      anonymousIdentity: 'Anonymous identity',
      authType: 'Security',
      body: 'Body',
      emailAddress: 'Email address',
      encodedParameters: 'Encoded parameters',
      eapMethod: 'EAP method',
      end: 'End',
      hidden: 'Hidden network',
      host: 'Host',
      identity: 'Identity',
      latitude: 'Latitude',
      location: 'Location',
      longitude: 'Longitude',
      manualCode: 'Manual code',
      message: 'Message',
      name: 'Name',
      number: 'Number',
      onboardingPayload: 'Onboarding payload',
      organisation: 'Organisation',
      password: 'Password',
      path: 'Path',
      payloadChunks: 'Payload chunks',
      payloadFormat: 'Payload format',
      phaseTwo: 'Phase two',
      phone: 'Phone',
      query: 'Query',
      scheme: 'Scheme',
      setupCode: 'Setup code',
      setupId: 'Setup ID',
      setupPayload: 'Setup payload',
      ssid: 'Network name',
      start: 'Start',
      subject: 'Subject',
      summary: 'Summary',
      target: 'Target',
      textLength: 'Text length',
      url: 'URL',
    },
    values: {
      assumedHttps: 'HTTPS assumed',
      matterBase38: 'Base-38 onboarding payload',
      noPassword: 'No password',
    },
  },
});
